version: '3'
services:
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: aVeryBadPassword
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
